name: Metrics
on:
  
  schedule: [{cron: "0 5 * * *"}]
 
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: alilo
          plugin_leetcode_sections: solved, skills, recent

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY}}
          COMMIT_BY_ME: "True"
          COMMIT_USERNAME: "alicemist"
          COMMIT_EMAIL: "alicemozkara@gmail.com"
          SHOW_TITLE: true
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
          SECTION_NAME: WAKA
      
 

          



