name: wakatime-stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "Updated time metrics"
          COMMIT_USERNAME: "alicemist"
          COMMIT_EMAIL: "alicemozkara@gmail.com"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY}}
          SECTION_NAME: 'time'
          SHOW_OS: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "True"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
